apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: katawolf
build:
  artifacts:
  - image: jtutzo/katawolf/frontend
    custom:
      buildCommand: docker build -t $IMAGE https://github.com/katawolf/frontend.git#master
  - image: jtutzo/katawolf/decisionservice
    custom:
      buildCommand: docker build -t $IMAGE https://github.com/katawolf/decisionservice.git#master
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - https://raw.githubusercontent.com/katawolf/frontend/master/k8s/configMap.yaml
      - https://raw.githubusercontent.com/katawolf/frontend/master/k8s/deployment.yaml
      - https://raw.githubusercontent.com/katawolf/frontend/master/k8s/service.yaml
      - https://raw.githubusercontent.com/katawolf/decisionservice/master/k8s/configMap.yaml
      - https://raw.githubusercontent.com/katawolf/decisionservice/master/k8s/deployment.yaml
      - https://raw.githubusercontent.com/katawolf/decisionservice/master/k8s/service.yaml
